server:
  port: 8500
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
filter.enable: true
filter.script: /Users/liguowang/workspace/utils/canal.adapter/conf/script
canal.conf:
  mode: kafka #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # kafka consumer
    kafka.bootstrap.servers: 192.168.135.119:9092,192.168.135.119:9093,192.168.135.119:9094
    kafka.enable.auto.commit: false
    kafka.auto.commit.interval.ms: 1000
    kafka.auto.offset.reset: latest
    kafka.request.timeout.ms: 40000
    kafka.session.timeout.ms: 30000
    kafka.isolation.level: read_committed
    kafka.max.poll.records: 1000

  canalAdapters:
    - instance: usercenter1
      groups:
        - groupId: usercenter-uc-temp-1
          outerAdapters:
            - name: rdb
              key: uc-mysql
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver
                jdbc.url: jdbc:mysql://192.168.134.55:3306/uc-wash?useUnicode=true
                jdbc.username: root
                jdbc.password: 123qwe